services:
  - type: web
    name: servidor-curso
    runtime: python
    plan: free
    region: oregon
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: SENHA_TURMA
        sync: false
      - key: FLASK_SECRET
        generateValue: true
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_REFRESH_TOKEN
        sync: false
      - key: DRIVE_PASTA_UPLOADS
        sync: false
      - key: DRIVE_PASTA_BASE
        sync: false
